###
### TERRAZAS ###
###
POST http://localhost:3000/api/terrazas
Content-Type: application/json

{
    "latitude":40.401574880819915,
    "longitude":-3.6909735773410772
}

###

POST http://localhost:3000/api/terrazas/barrio/LEGAZPI
Content-Type: application/json

{
    "latitude":40.401574880819915,
    "longitude":-3.6909735773410772
}

###
POST http://localhost:3000/api/terrazas/calle
Content-Type: application/json

{
    "calle": "asdfg"
}


###
### USUARIOS ###
###

###
# Registro
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

 {
    "username": "pistachu",
    "email": "ygomezma@gmail.com",
    "password": "12345"
  }

###
#Login
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

 {
    "email": "ygomezma@gmail.com",
    "password": "12345"
  }

###
#GetByEmail
GET http://localhost:3000/api/usuarios
Content-Type: application/json

 {
    "email": "ygomezma@gmail.com"
 }

###

###
### FAVORITOS ###
###

###
# getByUserId
GET http://localhost:3000/api/favoritos/1

###
# getByTerrazaId
POST http://localhost:3000/api/favoritos/terraza
Content-Type: application/json

 {
    "idTerraza": "712"
  }

###
# getByUserAndTerraza
POST http://localhost:3000/api/favoritos/getAll
Content-Type: application/json

 {
    "idUsuario": "63",
    "idTerraza": "32"
  }

###
# create
POST http://localhost:3000/api/favoritos/create
Content-Type: application/json

 {
    "idUsuario": "63",
    "idTerraza": "712"
  }

###
# delete
POST  http://localhost:3000/api/favoritos/delete
Content-Type: application/json

 {
    "idUsuario": "63",
    "idTerraza": "33"
  }

###
### COMENTARIOS ###
###

###
# getByTerrazaId
GET http://localhost:3000/api/comentarios/712

###
# getByUserAndTerraza
POST http://localhost:3000/api/comentarios/getAll
Content-Type: application/json

 {
    "idUsuario": "1",
    "idTerraza": "2336"
  }

###
# create
POST http://localhost:3000/api/comentarios/create
Content-Type: application/json

 {
    "idUsuario": "1",
    "idTerraza": "712",
    "comentario": "F en el chat"
  }

###
# delete
POST  http://localhost:3000/api/comentarios/delete
Content-Type: application/json

 {
    "id_comentario": "15"
  }

###
# patch
PATCH  http://localhost:3000/api/comentarios
Content-Type: application/json

 {
   "comentario": "Angular es muy intuitivo.",
   "id_comentario": "6"
  }


###
### PUNTUACIONES ###
###
###
# getByUserId
GET http://localhost:3000/api/puntuaciones/usuario/64
###
# getByTerrazaId
POST http://localhost:3000/api/puntuaciones/terraza
Content-Type: application/json

{
  "idTerraza": 2385
}
###



# create
POST http://localhost:3000/api/puntuaciones/create
Content-Type: application/json

{
    "puntuacion": 1,
    "idUsuario": 63,
    "idTerraza": 2385
}

###
POST http://localhost:3000/api/puntuaciones/puntuacion
Content-Type: application/json

{
  "idUsuario": 64,
  "idTerraza": 2385
}