###
### TERRAZAS ###
###
POST http://localhost:3000/api/terrazas
Content-Type: application/json

{
    "latitude":40.401574880819915,
    "longitude":-3.6909735773410772
}

###

POST http://localhost:3000/api/terrazas/barrio/LEGAZPI
Content-Type: application/json

{
    "latitude":40.401574880819915,
    "longitude":-3.6909735773410772
}


###
### USUARIOS ###
###

###
# Registro
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

 {
    "username": "pistachu",
    "email": "ygomezma@gmail.com",
    "password": "12345"
  }

###
#Login
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

 {
    "email": "ygomezma@gmail.com",
    "password": "12345"
  }

###
#GetByEmail
GET http://localhost:3000/api/usuarios
Content-Type: application/json

 {
    "email": "ygomezma@gmail.com"
 }

###

###
### FAVORITOS ###
###

###
# getByUserId
GET http://localhost:3000/api/favoritos/1

###
# getByUserAndTerraza
POST http://localhost:3000/api/favoritos/getAll
Content-Type: application/json

 {
    "idUsuario": "63",
    "idTerraza": "32"
  }

###
# create
POST http://localhost:3000/api/favoritos
Content-Type: application/json

 {
    "idUsuario": "63",
    "idTerraza": "33"
  }

###
# delete
DELETE  http://localhost:3000/api/favoritos
Content-Type: application/json

 {
    "idUsuario": "63",
    "idTerraza": "33"
  }


###
### PUNTUACIONES ###
###

###
# getByUserId
GET http://localhost:3000/api/puntuaciones/usuario/64

###
# getByTerrazaId
GET http://localhost:3000/api/puntuaciones/terraza/7


###
# create
POST http://localhost:3000/api/puntuaciones/create
Content-Type: application/json

{
    "puntuacion": 2,
    "idUsuario": 64,
    "idTerraza": 33
}

###
# delete
DELETE http://localhost:3000/api/puntuaciones/delete
Content-Type: application/json

{
    "idUsuario": 64,
    "idTerraza": 33
}

###
# update
PUT  http://localhost:3000/api/puntuaciones/update
Content-Type: application/json

{
    "puntuacion": 5,
    "idUsuario": 64,
    "idTerraza": 33
}
