###
### TERRAZAS ###
###
POST http://localhost:3000/api/terrazas
Content-Type: application/json

{
    "latitude":40.401574880819915,
    "longitude":-3.6909735773410772
}

###

POST http://localhost:3000/api/terrazas/barrio/LEGAZPI
Content-Type: application/json

{
    "latitude":40.401574880819915,
    "longitude":-3.6909735773410772
}


###
### USUARIOS ###
###

###
# Registro
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

 {
    "username": "pistachu",
    "email": "ygomezma@gmail.com",
    "password": "12345"
  }

###
#Login
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

 {
    "email": "ygomezma@gmail.com",
    "password": "12345"
  }

###
#GetByEmail
GET http://localhost:3000/api/usuarios
Content-Type: application/json

 {
    "email": "ygomezma@gmail.com"
 }

###

